# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZTC1Nu7UDXAZQP4ChtMMhpnGbUacB2N
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import pickle
import plotly.express as px
from datetime import datetime

# Load models
vectorizer = pickle.load(open("tfidf_vectorizer.pkl", "rb"))
category_model = pickle.load(open("category_model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))
anomaly_model = pickle.load(open("anomaly_model.pkl", "rb"))
forecast_model = pickle.load(open("forecast_model.pkl", "rb"))

st.set_page_config(page_title="AI Expense Analyzer", page_icon="💰")
st.title("💰 AI-Based Expense Pattern Analyzer")

# Upload CSV
uploaded_file = st.file_uploader("Upload your bank statement CSV", type="csv")
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    df['Date'] = pd.to_datetime(df['Date'])

    st.subheader("Raw Transactions")
    st.dataframe(df)

    # AI Categorization
    X_vect = vectorizer.transform(df["Description"])
    df["Predicted_Category"] = category_model.predict(X_vect)

    st.subheader("Transactions with AI Categorization")
    st.dataframe(df)

    # Anomaly Detection
    df_scaled = scaler.transform(df[["Amount"]])
    df["Anomaly"] = anomaly_model.predict(df_scaled)
    df["Anomaly"] = df["Anomaly"].apply(lambda x: "Anomaly" if x==-1 else "Normal")

    st.subheader("Anomalies in Transactions")
    st.dataframe(df[df["Anomaly"]=="Anomaly"])

    # Trend Analysis
    df['Month'] = df['Date'].dt.to_period('M')
    monthly = df.groupby('Month')['Amount'].sum().reset_index()
    monthly['Month'] = monthly['Month'].dt.to_timestamp()
    st.subheader("Monthly Spending Trend")
    fig = px.line(monthly, x="Month", y="Amount", title="Monthly Spending")
    st.plotly_chart(fig)

    # Forecast next month
    X_forecast = np.arange(len(monthly)+1).reshape(-1,1)
    forecast = forecast_model.predict(X_forecast)
    st.subheader("Spending Forecast for Next Month")
    st.write(f"Predicted spending: ₹{int(forecast[-1])}")

    # Top Categories
    top_cat = df.groupby('Predicted_Category')['Amount'].sum().sort_values(ascending=False).reset_index()
    st.subheader("Spending by Category")
    fig2 = px.pie(top_cat, values='Amount', names='Predicted_Category', title='Spending Distribution by Category')
    st.plotly_chart(fig2)

    # Recommendations
    st.subheader("Recommendations")
    highest_cat = top_cat.iloc[0]['Predicted_Category']
    st.write(f"⚠️ You are spending the most on **{highest_cat}**. Consider reducing this category to save money.")

