# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZTC1Nu7UDXAZQP4ChtMMhpnGbUacB2N
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.linear_model import LinearRegression
import plotly.express as px

# ----------------------------
# 1. Streamlit Page Setup
# ----------------------------
st.set_page_config(page_title="AI Expense Analyzer", page_icon="💰")
st.title("💰 AI-Powered Expense Pattern Analyzer")

# ----------------------------
# 2. Upload or Load Dataset
# ----------------------------
uploaded_file = st.file_uploader("Upload your bank statement CSV", type="csv")

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
else:
    # Fallback: load sample dataset
    try:
        df = pd.read_csv("/content/Personal_Finance_Dataset.csv")
        st.info("Using sample dataset (transactions.csv)")
    except:
        st.warning("Please upload a CSV file!")
        st.stop()

# Ensure Date is datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

st.subheader("Raw Transactions")
st.dataframe(df.head())

# ----------------------------
# 3. AI Categorization
# ----------------------------
# Train or load model
try:
    vectorizer = pickle.load(open("/content/tfidf_vectorizer.pkl", "rb"))
    category_model = pickle.load(open("/content/category_model.pkl", "rb"))
except:
    # Train simple model if not exists
    X = df['Transaction Description']
    y = df['Category'] if 'Category' in df.columns else pd.Series(["Other"]*len(df))
    vectorizer = TfidfVectorizer()
    X_vect = vectorizer.fit_transform(X)
    category_model = LogisticRegression(max_iter=500)
    category_model.fit(X_vect, y)
    # Save models
    pickle.dump(vectorizer, open("/content/tfidf_vectorizer.pkl", "wb"))
    pickle.dump(category_model, open("/content/category_model.pkl", "wb"))

# Predict categories
X_vect = vectorizer.transform(df['Transaction Description'])
df['Predicted_Category'] = category_model.predict(X_vect)

st.subheader("Transactions with AI Categorization")
st.dataframe(df[['Date','Transaction Description','Amount','Predicted_Category']].head())

# ----------------------------
# 4. Anomaly Detection
# ----------------------------
try:
    scaler = pickle.load(open("/content/scaler.pkl", "rb"))
    anomaly_model = pickle.load(open("/content/anomaly_model.pkl", "rb"))
except:
    scaler = StandardScaler()
    amount_scaled = scaler.fit_transform(df[['Amount']])
    anomaly_model = IsolationForest(contamination=0.05, random_state=42)
    anomaly_model.fit(amount_scaled)
    pickle.dump(scaler, open("/content/scaler.pkl", "wb"))
    pickle.dump(anomaly_model, open("/content/anomaly_model.pkl", "wb"))

# Detect anomalies
amount_scaled = scaler.transform(df[['Amount']])
df['Anomaly'] = anomaly_model.predict(amount_scaled)
df['Anomaly'] = df['Anomaly'].apply(lambda x: 'Anomaly' if x==-1 else 'Normal')

st.subheader("Anomalies Detected")
st.dataframe(df[df['Anomaly']=='Anomaly'])

# ----------------------------
# 5. Monthly Spending Trend
# ----------------------------
df['Month'] = df['Date'].dt.to_period('M')
monthly = df.groupby('Month')['Amount'].sum().reset_index()
monthly['Month'] = monthly['Month'].dt.to_timestamp()

st.subheader("Monthly Spending Trend")
fig = px.line(monthly, x='Month', y='Amount', title="Monthly Spending Trend")
st.plotly_chart(fig)

# ----------------------------
# 6. Forecast Next Month
# ----------------------------
try:
    forecast_model = pickle.load(open("/content/forecast_model.pkl", "rb"))
except:
    X_forecast = np.arange(len(monthly)).reshape(-1,1)
    y_forecast = monthly['Amount'].values
    forecast_model = LinearRegression()
    forecast_model.fit(X_forecast, y_forecast)
    pickle.dump(forecast_model, open("/content/forecast_model.pkl", "wb"))

X_forecast_full = np.arange(len(monthly)+1).reshape(-1,1)
forecast = forecast_model.predict(X_forecast_full)
st.subheader("Predicted Spending Next Month")
st.write(f"💵 Estimated spend: ₹{int(forecast[-1])}")

# ----------------------------
# 7. Spending by Category
# ----------------------------
top_cat = df.groupby('Predicted_Category')['Amount'].sum().reset_index().sort_values(by='Amount', ascending=False)
st.subheader("Spending Distribution by Category")
fig2 = px.pie(top_cat, values='Amount', names='Predicted_Category', title='Spending Distribution')
st.plotly_chart(fig2)

# ----------------------------
# 8. Recommendations
# ----------------------------
highest_cat = top_cat.iloc[0]['Predicted_Category']
st.subheader("Recommendations")
st.write(f"⚠️ You spent the most on **{highest_cat}**. Consider reducing expenses in this category to save money.")

